-- MySQL Script generated by MySQL Workbench
-- Sat Oct 19 10:54:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `installation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `installation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `unique_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_id_UNIQUE` (`unique_id` ASC))
ENGINE = InnoDB;
ALTER TABLE `installation` AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `execution_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `execution_description` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `installation_id` INT UNSIGNED NOT NULL,
  `execution_timestamp` DATETIME NOT NULL,
  `toolbox_launched` TINYINT NOT NULL,
  `queue_type` VARCHAR(64) NULL,
  `fp_set_type` VARCHAR(64) NULL,
  `off_heap_memory` INT UNSIGNED NOT NULL,
  `heap_memory` INT UNSIGNED NOT NULL,
  `jvm_architecture` VARCHAR(8) NOT NULL,
  `jvm_version` VARCHAR(12) NOT NULL,
  `jvm_vendor` VARCHAR(64) NOT NULL,
  `os_architecture` VARCHAR(8) NOT NULL,
  `os_version` VARCHAR(48) NOT NULL,
  `os_name` VARCHAR(24) NOT NULL,
  `core_count` INT UNSIGNED NOT NULL,
  `worker_count` INT UNSIGNED NOT NULL,
  `mode` VARCHAR(16) NOT NULL,
  `version` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `f_installation_id_idx` (`installation_id` ASC),
  CONSTRAINT `f_installation_id`
    FOREIGN KEY (`installation_id`)
    REFERENCES `installation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE `execution_description` AUTO_INCREMENT=1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
